INSERT INTO public.locals (name, address, type, state, city) VALUES
('Restaurante da Maria', 'Rua das Flores, 123', 'FOOD', 'SAO_PAULO', 'São Paulo'),
('Hospital São Lucas', 'Av. Brasil, 456', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Rio de Janeiro'),
('Posto do João', 'Rua das Palmeiras, 789', 'GAS_STATION', 'MINAS_GERAIS', 'Belo Horizonte'),
('Loja da Ana', 'Rua dos Pinheiros, 101', 'STORE', 'PARANA', 'Curitiba'),
('Pizzaria do Carlos', 'Av. das Águias, 555', 'FOOD', 'RIO_GRANDE_DO_SUL', 'Porto Alegre'),
('Hospital Santa Rita', 'Rua das Violetas, 222', 'HOSPITAL', 'SANTA_CATARINA', 'Florianópolis'),
('Posto do Pedro', 'Av. dos Girassóis, 333', 'GAS_STATION', 'ESPIRITO_SANTO', 'Vitória'),
('Loja do José', 'Rua das Margaridas, 444', 'STORE', 'BAHIA', 'Salvador'),
('Padaria da Ana', 'Av. das Rosas, 777', 'FOOD', 'AMAZONAS', 'Manaus'),
('Hospital Nossa Senhora', 'Rua das Orquídeas, 888', 'HOSPITAL', 'GOIAS', 'Goiânia'),
('Posto do Miguel', 'Av. dos Lírios, 999', 'GAS_STATION', 'CEARA', 'Fortaleza'),
('Loja da Maria', 'Rua das Tulipas, 111', 'STORE', 'PERNAMBUCO', 'Recife'),
('Restaurante do Joaquim', 'Av. dos Cravos, 222', 'FOOD', 'DISTRITO_FEDERAL', 'Brasília'),
('Hospital São Francisco', 'Rua das Begônias, 333', 'HOSPITAL', 'MATO_GROSSO', 'Cuiabá'),
('Posto da Ana', 'Av. das Azaléias, 444', 'GAS_STATION', 'ALAGOAS', 'Maceió'),
('Loja do Carlos', 'Rua das Hortênsias, 555', 'STORE', 'SERGIPE', 'Aracaju'),
('Cafeteria do Miguel', 'Av. das Camélias, 666', 'FOOD', 'RIO_GRANDE_DO_NORTE', 'Natal'),
('Hospital São José', 'Rua das Dálias, 777', 'HOSPITAL', 'ACRE', 'Rio Branco'),
('Posto do Antônio', 'Av. das Magnólias, 888', 'GAS_STATION', 'RONDONIA', 'Porto Velho'),
('Loja da Paula', 'Rua das Margaridas, 999', 'STORE', 'AMAPA', 'Macapá'),
('Churrascaria do João', 'Av. das Bromélias, 111', 'FOOD', 'TOCANTINS', 'Palmas'),
('Hospital Santo Antônio', 'Rua das Violetas, 222', 'HOSPITAL', 'MATO_GROSSO_DO_SUL', 'Campo Grande'),
('Posto da Maria', 'Av. das Orquídeas, 333', 'GAS_STATION', 'MARANHAO', 'São Luís'),
('Loja do Felipe', 'Rua das Tulipas, 444', 'STORE', 'PARAIBA', 'João Pessoa'),
('Café da Manhã da Ana', 'Av. dos Cravos, 555', 'FOOD', 'PARA', 'Belém'),
('Hospital São Marcos', 'Rua das Begônias, 666', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Niterói'),
('Posto do José', 'Av. das Azaléias, 777', 'GAS_STATION', 'SAO_PAULO', 'Campinas'),
('Loja do João', 'Rua das Hortênsias, 888', 'STORE', 'MINAS_GERAIS', 'Uberlândia'),
('Pizzaria do Miguel', 'Av. das Camélias, 999', 'FOOD', 'BAHIA', 'Feira de Santana'),
('Hospital da Cidade', 'Rua das Dálias, 111', 'HOSPITAL', 'PARANA', 'Londrina'),
('Posto da Ana', 'Av. das Magnólias, 222', 'GAS_STATION', 'GOIAS', 'Anápolis'),
('Loja da Carla', 'Rua das Margaridas, 333', 'STORE', 'AMAZONAS', 'Itacoatiara'),
('Restaurante da Joséfa', 'Av. das Bromélias, 444', 'FOOD', 'SANTA_CATARINA', 'Blumenau'),
('Hospital da Paz', 'Rua das Violetas, 555', 'HOSPITAL', 'ESPIRITO_SANTO', 'Vila Velha'),
('Posto do Luiz', 'Av. das Orquídeas, 666', 'GAS_STATION', 'PERNAMBUCO', 'Jaboatão dos Guararapes'),
('Loja do André', 'Rua das Tulipas, 777', 'STORE', 'DISTRITO_FEDERAL', 'Taguatinga'),
('Padaria da Maria', 'Av. dos Cravos, 888', 'FOOD', 'MATO_GROSSO', 'Várzea Grande'),
('Hospital São Lucas', 'Rua das Begônias, 999', 'HOSPITAL', 'CEARA', 'Juazeiro do Norte'),
('Posto do Marcos', 'Av. das Azaléias, 111', 'GAS_STATION', 'PIAUI', 'Teresina'),
('Loja da Camila', 'Rua das Hortênsias, 222', 'STORE', 'RORAIMA', 'Boa Vista'),
('Cafeteria do Joaquim', 'Av. das Camélias, 333', 'FOOD', 'TOCANTINS', 'Araguaína'),
('Hospital São João', 'Rua das Dálias, 444', 'HOSPITAL', 'ACRE', 'Cruzeiro do Sul'),
('Posto da Paula', 'Av. das Magnólias, 555', 'GAS_STATION', 'RONDONIA', 'Ji-Paraná'),
('Loja do Fernando', 'Rua das Margaridas, 666', 'STORE', 'AMAPA', 'Santana'),
('Churrascaria do Antônio', 'Av. das Bromélias, 777', 'FOOD', 'TOCANTINS', 'Gurupi'),
('Hospital Santo Antônio', 'Rua das Violetas, 888', 'HOSPITAL', 'MATO_GROSSO_DO_SUL', 'Dourados'),
('Posto do Renato', 'Av. das Orquídeas, 999', 'GAS_STATION', 'MARANHAO', 'Imperatriz'),
('Loja da Fernanda', 'Rua das Tulipas, 111', 'STORE', 'PARAIBA', 'Campina Grande'),
('Café da Manhã do José', 'Av. dos Cravos, 222', 'FOOD', 'PARA', 'Ananindeua'),
('Hospital São Marcos', 'Rua das Begônias, 333', 'HOSPITAL', 'RIO_DE_JANEIRO', 'São Gonçalo'),
('Posto da Carla', 'Av. das Azaléias, 444', 'GAS_STATION', 'SAO_PAULO', 'Santo André'),
('Loja do Roberto', 'Rua das Hortênsias, 555', 'STORE', 'MINAS_GERAIS', 'Contagem'),
('Pizzaria do Renato', 'Av. das Camélias, 666', 'FOOD', 'BAHIA', 'Itabuna'),
('Restaurante do Paulo', 'Rua das Acácias, 123', 'FOOD', 'SAO_PAULO', 'São José dos Campos'),
('Hospital São Pedro', 'Av. das Bromélias, 456', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Nova Iguaçu'),
('Posto da Laura', 'Rua das Orquídeas, 789', 'GAS_STATION', 'MINAS_GERAIS', 'Uberaba'),
('Loja do Eduardo', 'Av. das Rosas, 101', 'STORE', 'PARANA', 'Maringá'),
('Padaria da Patrícia', 'Rua das Violetas, 555', 'FOOD', 'RIO_GRANDE_DO_SUL', 'Caxias do Sul'),
('Hospital Nossa Senhora de Fátima', 'Av. das Hortênsias, 222', 'HOSPITAL', 'SANTA_CATARINA', 'Joinville'),
('Posto do Carlos', 'Rua das Tulipas, 333', 'GAS_STATION', 'ESPIRITO_SANTO', 'Cariacica'),
('Loja da Juliana', 'Av. das Azaléias, 444', 'STORE', 'BAHIA', 'Ilhéus'),
('Churrascaria do Pedro', 'Rua das Margaridas, 777', 'FOOD', 'AMAZONAS', 'Parintins'),
('Hospital Santa Maria', 'Av. dos Cravos, 888', 'HOSPITAL', 'GOIAS', 'Aparecida de Goiânia'),
('Posto da Patrícia', 'Rua das Dálias, 111', 'GAS_STATION', 'CEARA', 'Juazeiro do Norte'),
('Loja do Marcelo', 'Av. das Acácias, 222', 'STORE', 'PERNAMBUCO', 'Olinda'),
('Restaurante da Gabriela', 'Rua das Azaléias, 333', 'FOOD', 'DISTRITO_FEDERAL', 'Ceilândia'),
('Hospital São Francisco de Assis', 'Av. das Orquídeas, 444', 'HOSPITAL', 'MATO_GROSSO', 'Várzea Grande'),
('Posto da Carla', 'Rua das Bromélias, 555', 'GAS_STATION', 'ALAGOAS', 'Arapiraca'),
('Loja da Luciana', 'Av. dos Girassóis, 666', 'STORE', 'SERGIPE', 'Nossa Senhora do Socorro'),
('Cafeteria do Lucas', 'Rua das Hortênsias, 777', 'FOOD', 'RIO_GRANDE_DO_NORTE', 'Mossoró'),
('Hospital Santa Clara', 'Av. das Violetas, 888', 'HOSPITAL', 'ACRE', 'Rio Branco'),
('Posto do João', 'Rua das Orquídeas, 999', 'GAS_STATION', 'RONDONIA', 'Ariquemes'),
('Loja da Amanda', 'Av. das Margaridas, 111', 'STORE', 'AMAPA', 'Macapá'),
('Restaurante do Fernando', 'Rua das Dálias, 222', 'FOOD', 'TOCANTINS', 'Araguaína'),
('Hospital São Lucas', 'Av. das Acácias, 333', 'HOSPITAL', 'MATO_GROSSO_DO_SUL', 'Três Lagoas'),
('Posto do Gabriel', 'Rua das Azaléias, 444', 'GAS_STATION', 'MARANHAO', 'São José de Ribamar'),
('Loja do Mateus', 'Av. das Bromélias, 555', 'STORE', 'PARAIBA', 'Bayeux'),
('Padaria do João', 'Rua das Tulipas, 666', 'FOOD', 'PARA', 'Santarém'),
('Hospital São Rafael', 'Av. dos Cravos, 777', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Duque de Caxias'),
('Posto da Maria', 'Rua das Orquídeas, 888', 'GAS_STATION', 'SAO_PAULO', 'São Bernardo do Campo'),
('Loja do Bruno', 'Av. das Azaléias, 999', 'STORE', 'MINAS_GERAIS', 'Uberlândia'),
('Pizzaria da Ana', 'Rua das Hortênsias, 111', 'FOOD', 'BAHIA', 'Vitória da Conquista'),
('Hospital da Vida', 'Av. das Margaridas, 222', 'HOSPITAL', 'PARANA', 'Ponta Grossa'),
('Posto do Pedro', 'Rua das Acácias, 333', 'GAS_STATION', 'GOIAS', 'Rio Verde'),
('Loja da Jéssica', 'Av. das Rosas, 444', 'STORE', 'AMAZONAS', 'Parauapebas'),
('Restaurante da Fernanda', 'Rua das Violetas, 555', 'FOOD', 'SANTA_CATARINA', 'Itajaí'),
('Hospital São José', 'Av. dos Cravos, 666', 'HOSPITAL', 'ESPIRITO_SANTO', 'Serra'),
('Posto da Ana', 'Rua das Azaléias, 777', 'GAS_STATION', 'PERNAMBUCO', 'Petrolina'),
('Loja do Guilherme', 'Av. das Bromélias, 888', 'STORE', 'DISTRITO_FEDERAL', 'Guará'),
('Cafeteria da Maria', 'Rua das Orquídeas, 999', 'FOOD', 'MATO_GROSSO', 'Cáceres'),
('Hospital Santa Isabel', 'Av. das Acácias, 111', 'HOSPITAL', 'CEARA', 'Sobral'),
('Posto do Lucas', 'Rua das Margaridas, 222', 'GAS_STATION', 'PIAUI', 'Parnaíba'),
('Loja da Marcela', 'Av. das Azaléias, 333', 'STORE', 'RORAIMA', 'Boa Vista'),
('Churrascaria do Eduardo', 'Rua das Rosas, 444', 'FOOD', 'TOCANTINS', 'Araguatins'),
('Hospital Santo Antônio', 'Av. dos Cravos, 555', 'HOSPITAL', 'ACRE', 'Senador Guiomard'),
('Posto do André', 'Rua das Violetas, 666', 'GAS_STATION', 'RONDONIA', 'Cacoal'),
('Loja da Bruna', 'Av. das Orquídeas, 777', 'STORE', 'AMAPA', 'Santana'),
('Padaria do João', 'Rua das Flores, 456', 'FOOD', 'SAO_PAULO', 'São José dos Campos'),
('Hospital Santa Cruz', 'Av. Brasil, 789', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Nova Iguaçu'),
('Posto da Maria', 'Rua das Palmeiras, 101', 'GAS_STATION', 'MINAS_GERAIS', 'Uberaba'),
('Loja do Pedro', 'Rua dos Pinheiros, 202', 'STORE', 'PARANA', 'Maringá'),
('Restaurante da Ana', 'Av. das Águias, 303', 'FOOD', 'RIO_GRANDE_DO_SUL', 'Pelotas'),
('Hospital da Paz', 'Rua das Violetas, 404', 'HOSPITAL', 'SANTA_CATARINA', 'Joinville'),
('Posto do João', 'Av. dos Girassóis, 505', 'GAS_STATION', 'ESPIRITO_SANTO', 'Cachoeiro de Itapemirim'),
('Loja do Antônio', 'Rua das Margaridas, 606', 'STORE', 'BAHIA', 'Vitória da Conquista'),
('Cafeteria da Maria', 'Av. das Rosas, 707', 'FOOD', 'AMAZONAS', 'Parintins'),
('Hospital São Lucas', 'Rua das Orquídeas, 808', 'HOSPITAL', 'GOIAS', 'Anápolis'),
('Posto da Carla', 'Av. das Azaléias, 909', 'GAS_STATION', 'CEARA', 'Juazeiro do Norte'),
('Loja do Miguel', 'Rua das Tulipas, 111', 'STORE', 'PERNAMBUCO', 'Caruaru'),
('Restaurante do André', 'Av. dos Cravos, 222', 'FOOD', 'DISTRITO_FEDERAL', 'Ceilândia'),
('Hospital São Francisco', 'Rua das Begônias, 333', 'HOSPITAL', 'MATO_GROSSO', 'Várzea Grande'),
('Posto do Paulo', 'Av. das Azaléias, 444', 'GAS_STATION', 'ALAGOAS', 'Arapiraca'),
('Loja da Júlia', 'Rua das Hortênsias, 555', 'STORE', 'SERGIPE', 'Lagarto'),
('Padaria do Marcos', 'Av. das Camélias, 666', 'FOOD', 'RIO_GRANDE_DO_NORTE', 'Parnamirim'),
('Hospital Santa Rita', 'Rua das Dálias, 777', 'HOSPITAL', 'ACRE', 'Rio Branco'),
('Posto da Paula', 'Av. das Violetas, 888', 'GAS_STATION', 'RONDONIA', 'Ariquemes'),
('Loja do Renato', 'Rua das Tulipas, 999', 'STORE', 'AMAPA', 'Mazagão'),
('Churrascaria do José', 'Av. das Bromélias, 101', 'FOOD', 'TOCANTINS', 'Porto Nacional'),
('Hospital da Cidade', 'Rua das Orquídeas, 202', 'HOSPITAL', 'MATO_GROSSO_DO_SUL', 'Três Lagoas'),
('Posto do Joaquim', 'Av. das Azaléias, 303', 'GAS_STATION', 'MARANHAO', 'Imperatriz'),
('Loja da Beatriz', 'Rua das Margaridas, 404', 'STORE', 'PARAIBA', 'Bayeux'),
('Café da Manhã do Carlos', 'Av. dos Cravos, 505', 'FOOD', 'PARA', 'Santarém'),
('Hospital São Marcos', 'Rua das Begônias, 606', 'HOSPITAL', 'RIO_DE_JANEIRO', 'Duque de Caxias'),
('Posto da Jéssica', 'Av. das Azaléias, 707', 'GAS_STATION', 'SAO_PAULO', 'São Bernardo do Campo'),
('Loja do Tiago', 'Rua das Hortênsias, 808', 'STORE', 'MINAS_GERAIS', 'Governador Valadares'),
('Pizzaria do Pedro', 'Av. das Camélias, 909', 'FOOD', 'BAHIA', 'Barreiras'),
('Hospital São José', 'Rua das Dálias, 111', 'HOSPITAL', 'PARANA', 'Ponta Grossa'),
('Posto do Lucas', 'Av. das Violetas, 222', 'GAS_STATION', 'GOIAS', 'Rio Verde'),
('Loja da Juliana', 'Rua das Tulipas, 333', 'STORE', 'AMAZONAS', 'Parintins'),
('Restaurante da Beatriz', 'Av. das Bromélias, 444', 'FOOD', 'SANTA_CATARINA', 'Itajaí'),
('Hospital Nossa Senhora', 'Rua das Orquídeas, 555', 'HOSPITAL', 'ESPIRITO_SANTO', 'Cachoeiro de Itapemirim'),
('Posto da Fernanda', 'Av. das Azaléias, 666', 'GAS_STATION', 'PERNAMBUCO', 'Caruaru'),
('Loja do Gustavo', 'Rua das Margaridas, 777', 'STORE', 'DISTRITO_FEDERAL', 'Gama'),
('Padaria da Maria', 'Av. dos Cravos, 888', 'FOOD', 'MATO_GROSSO', 'Sinop'),
('Hospital Santo Antônio', 'Rua das Begônias, 999', 'HOSPITAL', 'CEARA', 'Juazeiro do Norte'),
('Posto do Tiago', 'Av. das Camélias, 101', 'GAS_STATION', 'PIAUI', 'Parnaíba'),
('Loja do Eduardo', 'Rua das Hortênsias, 202', 'STORE', 'RORAIMA', 'Boa Vista'),
('Cafeteria da Paula', 'Av. das Bromélias, 303', 'FOOD', 'TOCANTINS', 'Gurupi'),
('Hospital São João', 'Rua das Dálias, 404', 'HOSPITAL', 'ACRE', 'Cruzeiro do Sul'),
('Posto do Gustavo', 'Av. das Azaléias, 505', 'GAS_STATION', 'RONDONIA', 'Cacoal'),
('Loja da Alice', 'Rua das Tulipas, 606', 'STORE', 'AMAPA', 'Macapá'),
('Churrascaria da Paula', 'Av. das Camélias, 707', 'FOOD', 'TOCANTINS', 'Palmas');
